### ISSUE TITLE
mediapipe模型转换失败

### ISSUE THREAD

**Issue by reolf** [airockchip/rknn-toolkit#3]
操作系统：Ubuntu 18.04_x64
python 版本：3.8.19
rknn-toolkit 版本：1.7.5
target_platform: rv1109

对Mediapipe的 hand_landmark_lite.tflite模型进行转换时，加载tflite模型时报以下错误信息。请问有什么解决方案？

W rknn-toolkit version: 1.7.5
D Using CPPUTILS: True
I Start importing tflite...
I Model: hand_landmark_lite
I Version: 3
I Description: MLIR Converted.
I Subgraphs: 1
D import clients finished
D Convert layer conv_2d
D Convert layer depthwise_conv_2d
D Convert layer conv_2d
D Convert layer conv_2d
D Convert layer max_pool_2d
D Convert layer depthwise_conv_2d
D Convert layer conv_2d
D Convert layer add
D Convert layer conv_2d
D Convert layer depthwise_conv_2d
D Convert layer conv_2d
D Convert layer add
D Convert layer conv_2d
D Convert layer depthwise_conv_2d
D Convert layer conv_2d
D Convert layer conv_2d
D Convert layer depthwise_conv_2d
D Convert layer conv_2d
D Convert layer add
D Convert layer conv_2d
D Convert layer depthwise_conv_2d
D Convert layer conv_2d
D Convert layer conv_2d
D Convert layer depthwise_conv_2d
D Convert layer conv_2d
D Convert layer add
D Convert layer conv_2d
D Convert layer depthwise_conv_2d
D Convert layer conv_2d
D Convert layer add
D Convert layer conv_2d
D Convert layer depthwise_conv_2d
D Convert layer conv_2d
D Convert layer conv_2d
D Convert layer depthwise_conv_2d
D Convert layer conv_2d
D Convert layer add
D Convert layer conv_2d
D Convert layer depthwise_conv_2d
D Convert layer conv_2d
D Convert layer add
D Convert layer conv_2d
D Convert layer depthwise_conv_2d
D Convert layer conv_2d
D Convert layer conv_2d
D Convert layer depthwise_conv_2d
D Convert layer conv_2d
D Convert layer add
D Convert layer conv_2d
D Convert layer depthwise_conv_2d
D Convert layer conv_2d
D Convert layer add
D Convert layer conv_2d
D Convert layer depthwise_conv_2d
D Convert layer conv_2d
D Convert layer add
D Convert layer conv_2d
D Convert layer depthwise_conv_2d
D Convert layer mean
D Convert layer dequantize
D Convert layer dequantize
D Convert layer fully_connected
W Tensor b'model_1/model/conv_handedness/BiasAdd/ReadVariableOp/resource_dequantize' has no buffer, init to zeros.
D Convert layer logistic
D Convert layer dequantize
D Convert layer dequantize
D Convert layer fully_connected
W Tensor b'model_1/model/conv_handflag/BiasAdd/ReadVariableOp/resource_dequantize' has no buffer, init to zeros.
D Convert layer logistic
D Convert layer dequantize
D Convert layer dequantize
D Convert layer fully_connected
W Tensor b'model_1/model/conv_landmarks/BiasAdd/ReadVariableOp/resource_dequantize' has no buffer, init to zeros.
D Convert layer dequantize
D Convert layer dequantize
D Convert layer fully_connected
W Tensor b'model_1/model/conv_world_landmarks/BiasAdd/ReadVariableOp/resource_dequantize' has no buffer, init to zeros.
E Invalid tensor id(2), tensor(@model_1/model/conv_handedness/BiasAdd/ReadVariableOp/resource_dequantize_93:out0)
E Catch exception when loading tflite model: ./hand_landmark_lite.tflite!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/converter/tflite_loader.py", line 575, in rknn.base.RKNNlib.converter.tflite_loader.ModelParser.parse
E   File "rknn/base/RKNNlib/converter/tflite_loader.py", line 546, in rknn.base.RKNNlib.converter.tflite_loader.ModelParser._build_connections
E   File "rknn/base/RKNNlib/layer/RKNNlayer.py", line 144, in rknn.base.RKNNlib.layer.RKNNlayer.RKNNLayer.add_input
E   File "rknn/base/RKNNlib/layer/RKNNlayer.py", line 26, in rknn.base.RKNNlib.layer.RKNNlayer.IoStruct.add
E   File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Invalid tensor id(2), tensor(@model_1/model/conv_handedness/BiasAdd/ReadVariableOp/resource_dequantize_93:out0)
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

**Comment by kyn817046** [comment]
请问解决了吗？
